2017-01-05 12:23:00 : StockKLine LINE 124   ERROR    Internal Server Error: /stock/
Traceback (most recent call last):
  File "D:\Program Files\python2.7\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Program Files\python2.7\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\python2.7\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:/py/stockweb\stock\views.py", line 61, in getCowStock
    currentPriceOfLowRateTrue,currentPriceOfLowRateFalse = StockTools().getCurrentPriceOfLowRate(content)
  File "E:/py/stockweb\stock\com\zw\stock\tools\stock_tools.py", line 107, in getCurrentPriceOfLowRate
    exist.update(code=key)
AttributeError: 'Current_Price_Of_Low_Rate' object has no attribute 'update'
